services:
  - type: web
    name: fb-posting-app
    env: python
    buildCommand: |
      mkdir -p templates uploads
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    staticPublishPath: ./templates # Ensure templates directory is included
